---
deployment:
  tasks:
    - export DEPLOYPATH=/home/miorpaco/miorpa-repo/
    - export PUBLICPATH=/home/miorpaco/notify.miorpa.com/

    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $PUBLICPATH

    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH

    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH

    - /opt/cpanel/ea-php82/root/usr/bin/php /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --working-dir=$DEPLOYPATH

    - /bin/cp -R public/. $PUBLICPATH